### ISSUE TITLE
New instructions on AsmBlocks

### ISSUE THREAD

**Issue by eybisi** [eset/stadeo#2]
```
loc_key_12
CMP        RCX, 0x0
JZ         loc_25e10
->      c_next:loc_key_13       c_to:loc_25e10
Traceback (most recent call last):
  File "x/stadeo/stadeo/cff/cff_strategies.py", line 63, in solve_loop
    recognizer.recognize(only_one, context)
  File "x/stadeo/stadeo/cff/cff_recognizer.py", line 416, in recognize
    irb_bak = self._recog_init(merging_var_candidates)
  File "x/stadeo/stadeo/cff/cff_recognizer.py", line 317, in _recog_init
    self.ircfg = self.ir_arch.new_ircfg_from_asmcfg(self.asmcfg)
  File "y/lib/python3.8/site-packages/miasm/ir/ir.py", line 745, in new_ircfg_from_asmcfg
    self.add_asmblock_to_ircfg(block, ircfg)
  File "y/lib/python3.8/site-packages/miasm/ir/ir.py", line 832, in add_asmblock_to_ircfg
    split = self.add_instr_to_current_state(
  File "y/lib/python3.8/site-packages/miasm/ir/analysis.py", line 82, in add_instr_to_current_state
    assignblk, ir_blocks_extra = self.instr2ir(instr)
  File "y/lib/python3.8/site-packages/miasm/ir/ir.py", line 749, in instr2ir
    ir_bloc_cur, extra_irblocks = self.get_ir(instr)
  File "y/lib/python3.8/site-packages/miasm/arch/x86/sem.py", line 5812, in get_ir
    self.mod_pc(instr, instr_ir, extra_ir)
  File "y/lib/python3.8/site-packages/miasm/arch/x86/sem.py", line 5934, in mod_pc
    pc_fixed = {self.pc: m2_expr.ExprInt(instr.offset + instr.l, 64)}
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```
I have a control flow obfuscated elf library file. After upgrading stadeo to latest miasm, I get this error which means newly created instructions after processing jump table doesn't have offset & l parameters. So script cannot convert it to IRCFG. Is this because of new internals of miasm ?

**Comment by eybisi** [comment]
https://github.com/cea-sec/miasm/pull/1277#issuecomment-678623957 as stated here if asmblocks didn't created by disassembler, instructions doesn't have any address assigned to them

**Comment by nofiv** [comment]
Hello @eybisi, the latest version of Miasm doesn't definitely work with Stadeo, however I believe that it would have crashed much sooner - for example [get_ira ](https://github.com/eset/stadeo/blob/master/stadeo/utils/extended_asmcfg.py#L11)is no longer a part of [disasm_cb](https://github.com/cea-sec/miasm/blob/master/miasm/analysis/disasm_cb.py). You are probably still using an older version of Miasm.

Anyway, thanks for reporting the issue. We create some instructions without offset and size by hand and Miasm sometimes doesn't expect the attributes to be None. I believe that [this version](https://github.com/nofiv/stadeo/tree/moc_pc_fix) should fix the error for you, does it work?

**Comment by eybisi** [comment]
It works thanks. I patched older APIs to newer ones so thats why it didn't crash.
